### ISSUE TITLE
Computation of the identification Model

### ISSUE THREAD

**Issue by NuBot-Cc** [TUM-ICS/BIRDy#8]
Dear Dr. Leboutet

Thank you very much for conducting comprehensive, practical, and outstanding research. While studying your paper and code, I am interested in developing symbolic models for dynamic symbol models.  Here is a question that I would like to ask you.  When computing the symbolic identification model, it takes a very long time, and it hasn't finished even after two days. 

The main issue is that it keeps getting stuck at this particular line of code (computeIdentificationModel.m line119)：
`matlabFunction(Y,'File','Benchmark/Robot_Generated_Data/Y_r_handle', 'Vars', {robot.symbolicParameters.Q, robot.symbolicParameters.Qp, robot.symbolicParameters.Qpp, robot.symbolicParameters.Geometry, robot.symbolicParameters.Gravity},'Optimize',true);
`
 I am not sure if it hasn't finished computing or if the computer hangs due to the extended time spent here or if there might be an issue with  generating Y Function by“matlabFunction” and saving it to the “Y_r_handle” file. When I open Y_r_handle.m,  it is empty.
My computer's CPU is i7-11th Gen, GPU is 3060, and I am using matlab2019b. How long does this step approximately take, and should I wait longer? 

Looking forward to your reply and appreciating your help.

**Comment by quentin-leboutet** [comment]
Hi, 
thanks for the nice comments. Symbolic computations work well for low-dimensional mechanisms (typically not more than 7DoF) but do not really scale to more complex systems. This turns out to be one of the main weaknesses of BIRDy. If you are willing to identify such systems, or even floating base systems, you may want to consider a python library named FIGAROH which was recently released by the LAAS in France. The [research paper](https://laas.hal.science/hal-04234676v2) and [code repository](https://gitlab.laas.fr/gepetto/figaroh/-/tree/devel) are available online.

**Comment by NuBot-Cc** [comment]
Thank you! I will continue to read the paper and the code repository. 

I encountered this problem when generating the TX40 symbolic model instead of generating a model for another robot. 
May I ask that how do you get or compute the symblic model (especially the matrix Y) of the example robots (TX40) in your paper，Do you also use LAAS to solve this problem？ 

Thank you very much!

**Comment by quentin-leboutet** [comment]
Hello, 

please check the following [issue](https://github.com/TUM-ICS/BIRDy/issues/9#issuecomment-1999295175).

Regards,

Quentin
